# Site settings
title: Coding for a Creative
header-img: img/home-bg.png
email: ania.hammar@gmail.com
copyright_name: aniah822
description: > # this means to ignore newlines until "baseurl:"
  Where creativity meets structure
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: aniahammarmusic
github_username:  aniah822
learn_profile: aniah822
email_username: ania.hammar@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
